### ISSUE TITLE
Review usage of exceptions and try/except blocks

### ISSUE THREAD

**Issue by mratsim** [status-im/nim-blscurve#57]
I don't think we should have any exceptions or try/except block at all in a crypto backend.

This was triggered on an empty aggregate test:

![image](https://user-images.githubusercontent.com/22738317/83011517-4bd3ff80-a01a-11ea-894d-6c91b00b8f54.png)

https://github.com/status-im/nim-blscurve/blob/b435f1a7296fceda8a68aaca391e6d76b2c632d3/blscurve/common.nim#L668-L677

And there is another one here:

https://github.com/status-im/nim-blscurve/blob/b435f1a7296fceda8a68aaca391e6d76b2c632d3/blscurve/common.nim#L594-L601

i.e. `{.push raises: [].}` and introduce an exception-free hexToSeqBytes

**Comment by arnetheduck** [comment]
oops - this looks like a bug in `hexSeqToByte` which should raise a `ValueError` - that said, I'd agree in general but for that we need to do some groundwork (error-free parser, RNG)

**Comment by arnetheduck** [comment]
clear your package cache, this was fixed long ago
