### ISSUE TITLE
Compiled version

### ISSUE THREAD

**Issue by mmathys** [status-im/nim-blscurve#62]
Hello,

this repo looks very interesting. I would like to use this library for another project (written in Go). 

Therefore I was wondering whether there is a precompiled binary available, which supports the ETH 2.0 interface as stated [here](https://github.com/ethereum/eth2.0-specs/blob/v0.10.1/specs/phase0/beacon-chain.md#bls-signatures).

That way, I could test and use this library.

Thanks in advance.

**Comment by mratsim** [comment]
The only purpose is supporting Eth 2 ;).

Would you also need support for EIP 2333 for secret key generation and "infinite" public keys/wallets derivation?
https://eips.ethereum.org/EIPS/eip-2333

**Comment by mmathys** [comment]
No, I don't need support for EIP 2333.

I would only need key generation, signing, signature aggregation,
verification.

**Comment by mmathys** [comment]
Does somebody maybe have a hint whether this is possible? :)

**Comment by zah** [comment]
It's definitely possible, but you may need to learn a bit more how [Nim can interop will other languages](https://nim-lang.github.io/Nim/backends.html#interfacing).

The closest example you can study is the [libnimbus](https://github.com/status-im/nimbus/tree/master/wrappers) library that we prepare precisely for the purpose of calling Nim code from our Status Go implementation. There are important details both in the code and in the associated Makefiles.

**Comment by mmathys** [comment]
I ended up using https://github.com/herumi/bls-eth-go-binary instead

**Comment by mmathys** [comment]
Thank you for your help nonetheless
